### PR TITLE
Check out IDF file from MBL issue1437_district_heating_cooling

### LINKED ISSUE #105: [5/29] Latest updates to issue 1437_district_heating_cooling break GMT
To recreate

* checkout the latest version of the `issue1437_district_heating_cooling` branch of MBL
* Make sure that MODELICAPATH is set to the correct MBL directory
* Make sure docker is running (simulations run in Docker)
* run `py.test` on latest develop of GMT or run a specific Spawn model for expediency (`py.test tests/model_connectors/test_spawn.py::SpawnModelConnectorSingleBuildingTest::test_spawn_to_modelica_and_run`)
* Results will be in the `geojson-modelica-translator/tests/model_connectors/output/spawn_single_results` folder

```
[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types
EnergyPlus Starting
EnergyPlus, Version 9.3.0-278a3caa5c, YMD=2020.05.18 15:21
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
EnergyPlus Run Time=00hr 00min  0.16sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.
```

### PR DESCRIPTION
**Pull request by AntoineGautier**
This closes #105.
See [my comment](https://github.com/urbanopt/geojson-modelica-translator/issues/105#issuecomment-630326788) in the issue to avoid similar CI break in the future.

### CODE REVIEW

**Comment by AntoineGautier** [comment]
@nllong Updating the IDF file fixed the issue related to the error message reported in  #105.
However I get a different error now.
```
*** Compiling spawn_single.Loads.B5a6b99ec37f4de7f94020090.CouplingETS_SpawnBuilding
sources/ModelicaInternal_fullPathName.c: In function 'main':
sources/ModelicaInternal_fullPathName.c:56:24: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             fullName_v = ModelicaInternal_fullPathName(name_v);
                        ^
/usr/local/JModelica/bin/../lib/RuntimeLibrary/libModelicaExternalC.a(ModelicaInternal.c.o): In function `ModelicaInternal_temporaryFileName':
/usr/local/src/JModelica/ThirdParty/MSL/Modelica/Resources/C-Sources/ModelicaInternal.c:657: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
sources/ModelicaStrings_substring.c: In function 'main':
sources/ModelicaStrings_substring.c:64:22: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             result_v = ModelicaStrings_substring(string_v, tmp_1, tmp_2);
                      ^
Error at line 34, column 6, in file '/mnt/home/agautier/gitrepo/geojson-modelica-translator/tests/model_connectors/output/spawn_single/Loads/B5a6b99ec37f4de7f94020090/CouplingETS_SpawnBuilding.mo':
  Cannot find component declaration for nPorts_a
Error at line 35, column 6, in file '/mnt/home/agautier/gitrepo/geojson-modelica-translator/tests/model_connectors/output/spawn_single/Loads/B5a6b99ec37f4de7f94020090/CouplingETS_SpawnBuilding.mo':
  Cannot find component declaration for nPorts_b
```
This seems to be due to the commit `a13169dc0780cfa2e892ddf8d52933ec93f0d9bf` which modified the fluid port declaration in `geojson_modelica_translator/model_connectors/templates/PartialBuilding.mo`.
Note that the modification of the `PartialBuilding` class we discussed in the technical iteration meeting (dedicated ports for heating and chilled water) are addressed in MBL [#1858](https://github.com/lbl-srg/modelica-buildings/issues/1858) and will be pushed soon to issue1437_district_heating_cooling.

**Comment by nllong** [comment]
Hmm. Yes, that looks like another issue possibly related to the updated MBL code. It sounds like once you push #1858 to this branch then things will be resolved, correct? If so, then I think we leave this open until that happens.

Da: Antoine Gautier <notifications@github.com>
Risposta: urbanopt/geojson-modelica-translator <reply@reply.github.com>
Data: martedì 19 maggio 2020 12:50
A: urbanopt/geojson-modelica-translator <geojson-modelica-translator@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [urbanopt/geojson-modelica-translator] Check out IDF file from MBL issue1437_district_heating_cooling (#110)


@nllong<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=02%7C01%7Cnicholas.long%40nrel.gov%7C8b06641f0ec54c57d9f408d7fc257cde%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637255110256475400&sdata=RHnCRQ5XREXrPaMikWGmF5ZhfhUpHkEmvPUw5fGjt4g%3D&reserved=0> Updating the IDF file fixed the issue related to the error message reported in #105<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Furbanopt%2Fgeojson-modelica-translator%2Fissues%2F105&data=02%7C01%7Cnicholas.long%40nrel.gov%7C8b06641f0ec54c57d9f408d7fc257cde%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637255110256485389&sdata=3xzDUe00LmdZ00gvxMeSFOLEW4Uptxj5i8V5DVw3eGI%3D&reserved=0>.
However I get a different error now.

*** Compiling spawn_single.Loads.B5a6b99ec37f4de7f94020090.CouplingETS_SpawnBuilding

sources/ModelicaInternal_fullPathName.c: In function 'main':

sources/ModelicaInternal_fullPathName.c:56:24: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]

             fullName_v = ModelicaInternal_fullPathName(name_v);

                        ^

/usr/local/JModelica/bin/../lib/RuntimeLibrary/libModelicaExternalC.a(ModelicaInternal.c.o): In function `ModelicaInternal_temporaryFileName':

/usr/local/src/JModelica/ThirdParty/MSL/Modelica/Resources/C-Sources/ModelicaInternal.c:657: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

sources/ModelicaStrings_substring.c: In function 'main':

sources/ModelicaStrings_substring.c:64:22: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]

             result_v = ModelicaStrings_substring(string_v, tmp_1, tmp_2);

                      ^

Error at line 34, column 6, in file '/mnt/home/agautier/gitrepo/geojson-modelica-translator/tests/model_connectors/output/spawn_single/Loads/B5a6b99ec37f4de7f94020090/CouplingETS_SpawnBuilding.mo':

  Cannot find component declaration for nPorts_a

Error at line 35, column 6, in file '/mnt/home/agautier/gitrepo/geojson-modelica-translator/tests/model_connectors/output/spawn_single/Loads/B5a6b99ec37f4de7f94020090/CouplingETS_SpawnBuilding.mo':

  Cannot find component declaration for nPorts_b

This seems to be due to the commit a13169dc0780cfa2e892ddf8d52933ec93f0d9bf which modified the fluid port declaration in geojson_modelica_translator/model_connectors/templates/PartialBuilding.mo.
Note that the modification of the PartialBuilding class we discussed in the technical iteration meeting (dedicated ports for heating and chilled water) are addressed in MBL #1858<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flbl-srg%2Fmodelica-buildings%2Fissues%2F1858&data=02%7C01%7Cnicholas.long%40nrel.gov%7C8b06641f0ec54c57d9f408d7fc257cde%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637255110256485389&sdata=jQPU%2Fj60odOR7YE4CGzFH4nBFrUBWBykeOz3mIP8OAc%3D&reserved=0> and will be pushed soon to issue1437_district_heating_cooling.

**Comment by AntoineGautier** [comment]
@nllong I am not sure because I am not fully aware of the software stack. Do the tests that run the Spawn models use `geojson_modelica_translator/model_connectors/templates/PartialBuilding.mo` or do they rather use the class from MBL branch `issue1437_district_heating_cooling`?

**Comment by nllong** [comment]
We created a copy of the partialbuidling.mo with some small updates as we wait for issue1437 to catch up. We don't plan on keeping any files in the GMT that are in MBL.

**Comment by AntoineGautier** [comment]
@nllong The error log included in my previous message was due to a different branch than `issue1437_district_heating_cooling` checked out in the MBL directory on my MODELICAPATH.
When checking out the correct branch all tests pass on my system (see snapshot) but the Travis build stalls for a reason I cannot figure out. Do you have any guess?
Screen Shot 2020-06-02 at 4 14 21 PM

**Comment by nllong** [comment]
I think you need to remove this line from travis.yml. I locked down the version so that we could keep developing. 

https://github.com/urbanopt/geojson-modelica-translator/blob/issue105_updateIDF/.travis.yml#L25

**Comment by nllong** [comment]
Looks like the tests have passed: https://travis-ci.org/github/urbanopt/geojson-modelica-translator/builds/693881771 , thanks for fixing this.

**Comment by AntoineGautier** [comment]
@nllong Sorry I missed your message and just pushed a dummy commit to trigger CI testing.

**Pull request merged**
