### PR TITLE
[refactor/scaffold] Move model connectors to lookup

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
The to_modeilca method was too rigid and only handled a single load model type (e.g., spawn or time series) at a time.

#### What does this PR accomplish?
* Support multiple load models at a time
* Rename load types to [spawn, rc, and time_series] and update schema

#### How should this be manually tested?
`py.test`

#### What are the relevant tickets?
#169 
There will be other updated includes
  * abstract out an isolated building vs ETS building to remove redundant code
  * move district test to place loads in the correct location, create multiple building loads as defined in geojson

### CODE REVIEW

**Review by vtnate — APPROVED** [review]
I love it when a PR has more deleted lines than added. 😁

**Comment by nllong** [comment]
@amyeallen1 and @vtnate  -- I'm going to hold off merging this down as it will break your various branches.

**Comment by amyeallen1** [comment]
Thanks, Nick!

**Comment by vtnate** [comment]
@nllong Did #184 break this? Lines 327-328 in the Travis output make it look like it's not my fault, but 329-330 have my fingerprints on them... 😟

**Comment by nllong** [comment]
Well, yes it did, but that is only because I have changed the assumption that a `model_connector` is for only one load/building now. I am fixing it.

**Pull request merged**
