### PR TITLE
4GDH package_first GMT draft

### PR DESCRIPTION
**Pull request by Helarga**
GMT Templates and modelica models for the 4GDH system 

relevant tickets:
https://github.com/urbanopt/geojson-modelica-translator/issues/108
https://github.com/urbanopt/geojson-modelica-translator/issues/141

### CODE REVIEW

**Comment by nllong** [comment]
It appears that you branched off an older version of the gmt/develop branch and I'm trying to figure out which files are really "new".  Specifically, did you update the PartialBuilding.mo, PartialConnection2Pipe.mo, and PartialDistribution2Pipe.mo files or can we point this back to the versions in the MBL?

**Comment by Helarga** [comment]
> It appears that you branched off an older version of the gmt/develop branch and I'm trying to figure out which files are really "new". Specifically, did you update the PartialBuilding.mo, PartialConnection2Pipe.mo, and PartialDistribution2Pipe.mo files or can we point this back to the versions in the MBL?

sorry !, yes we can point these models back to MBL.

**Comment by nllong** [comment]
Much better, thanks!

**Comment by Helarga** [comment]
> Much better, thanks!
ma certo!
let me also update the path of all components at the MBL

**Pull request merged**
