### PR TITLE
Use weather file from sdk if available

### LINKED ISSUE #410: weather file from SDK workflow in .mos
~Wetbulb .mos file is a different ticket.~

the weather file has to be set manually right now when using the SDK CLI workflow. It should be an input to the CLI so the file doesn't have to be edited by hand afterwards.

-Nate and Amy to consult 

-Hiccup with CVOde in simulation

### PR DESCRIPTION
**Pull request by vtnate**
#### Any background context you want to provide?
Uses UO sdk weather for cooling plant
#### What does this PR accomplish?
1. Reads weather file from sdk feature file into sys-param file
2. Copies the appropriate mos file down from energyplus.net/weather
3. Puts it in the users MBL, and in the cooling plant mofile
#### How should this be manually tested?
1. Run the cli command `poetry run uo_des run-model` to run the temporarily saved modelica model
#### What are the relevant tickets?
Resolves #410 

#### Todo:
1. Confirm the url error-handling works as intended.
2. Save the downloaded mos_weather_file to a different location. Places I think would be appropriate:
    -  In the sdk weather folder
    -  In the users modelica model folder (in this case, `./model_from_sdk`)

### CODE REVIEW

**Comment by vtnate** [comment]
The `temporary` commits are here for diagnostics and should be reverted before merging.

**Review by vtnate — COMMENTED** [review]
I'm sure I wrote that comment about my own code. Not you at all @macintoshpie !

**Comment by nllong** [comment]
I need this PR merged to fix the error I am seeing in #396. Any issue if I review and fix any issues?

**Comment by vtnate** [comment]
> I need this PR merged to fix the error I am seeing in #396. Any issue if I review and fix any issues?

@nllong Before merging we should delete `./model_from_sdk/` and `yyy.json` as they are solely for dev testing.

**Comment by nllong** [comment]
> > I need this PR merged to fix the error I am seeing in #396. Any issue if I review and fix any issues?
> 
> @nllong Before merging we should delete `./model_from_sdk/` and `yyy.json` as they are solely for dev testing.

sounds good. I'm trying to get this to pass today and I'll create a PR for you to review...

**Comment by vtnate** [comment]
@nllong 😱 The tests passed?! 🎉

**Comment by nllong** [comment]
appears that we must build all new district energy systems in san Francisco now. Or at a minimum create district water in san Francisco, then pipe to chicago/new york/denver, haha.

**Comment by vtnate** [comment]
Pipeline companies are going to make a mint

**Comment by nllong** [comment]
> Pipeline companies are going to make a mint

haha. can you review once more, then merge if good, thanks!

**Review by nllong — APPROVED** [review]
oh, i was the reviewer!

**Pull request merged**
