### PR TITLE
use medium office from 2004

### PR DESCRIPTION
**Pull request by nllong**
#### Any background context you want to provide?
The time series model for the district_heating_and_cooling was the swiss res model.  When replacing with the large office from 2013 in 5B, the model started crashing.

#### What does this PR accomplish?
* Change to medium office from 2004.
 
#### How should this be manually tested?
py.test

#### What are the relevant tickets?
N/A

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by macintoshpie** [comment]
@nllong I corrected the filename for the load data so now the modelica packages build and compile successfully. But now we're running into the issue of the JModelica solver getting stuck again, meaning it runs indefinitely. Last time this happened I think we fixed it by tweaking some (seemingly) random factors. Here's the tail of the stdout logs:

```
 Integrator time: 9.520174e+03
 Integrator time: 2.727546e+04
[CVode Warning] Internal t = 27286.4 and h = 4.56213e-13 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 4.56213e-13 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 1.14053e-12 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 1.14053e-12 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 7.12833e-13 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 7.12833e-13 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 1.78208e-12 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 1.78208e-12 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 1.1138e-12 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] Internal t = 27286.4 and h = 1.1138e-12 are such that t + h = t on the next step. The solver will continue anyway.
[CVode Warning] The above warning has been issued mxhnil times and will not be issued again for this problem.
```

Here's the tail of the pyfmi output
```
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error] <ModelEquationsEvaluationFailed category="error">Error evaluating model equations.</ModelEquationsEvaluationFailed>
FMIL: module = Model, log level = 2: [INFO][FMU status:Error]       <KinsolError category="error">
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]         Error occured in <value name="function">KINSol</value> at <value name="t">        2.7286378642810505E+04</value> when solving <value name="block">"3"</value>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]         <value name="msg">"The line search algorithm was unable to find an iterate sufficiently distinct from the current iterate."</value>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]         <value name="functionL2Norm">        1.0000000112619289E-08</value>, <value name="scaledStepLength">        1.3239934084349097E-02</value>, <value name="tolerance">        1.0000000000000000E-08</value>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]       </KinsolError>
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning]     <NonConverge category="warning">The equations with initial scaling didn't converge to a solution in <value name="block">"3"</value></NonConverge>
FMIL: module = Model, log level = 2: [INFO][FMU status:Error]       <KinsolError category="error">
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]         Error occured in <value name="function">KINSol</value> at <value name="t">        2.7286378642810505E+04</value> when solving <value name="block">"3"</value>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]         <value name="msg">"The line search algorithm was unable to find an iterate sufficiently distinct from the current iterate."</value>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]         <value name="functionL2Norm">        7.8390237636948454E-02</value>, <value name="scaledStepLength">        1.3239932160473573E-02</value>, <value name="tolerance">        1.0000000000000000E-08</value>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]       </KinsolError>
FMIL: module = Model, log level = 2: [ERROR][FMU status:Error]     <Error category="error">Could not converge after re-scaling equations in <value name="block">"3"</value></Error>
```

**Comment by nllong** [comment]
Thanks for fixing the file name. I'll look at this again.

**Comment by nllong** [comment]
@macintoshpie  -- can you take a look when running this:

` py.test tests/model_connectors/test_district_system.py::DistrictSystemTest::test_district_system`

which shows this error

```
Syntax error at line 99, column 39, in file '/mnt/Users/nlong/working/urban-analysis/geojson-modelica-translator/tests/model_connectors/output/district_system/Districts/DistrictEnergySystem.mo':
     Unexpected token: "/"
```

**Comment by AntoineGautier** [comment]
On my system, only one model fails to simulate.
```
======================================================================= short test summary info ========================================================================
FAILED tests/model_connectors/test_district_heating_and_cooling_systems.py::DistrictHeatingAndCoolingSystemsTest::test_district_heating_and_cooling_systems - Asserti...
========================================================= 1 failed, 61 passed, 1 skipped in 433.87s (0:07:13) ==========================================================
```

I did not manage to solve the issue but my first attempt made me think that it requires some additional work on the plant and ETS models. I provide my notes hereunder for reference. 

From the log file, the block that triggers the convergence error is nº2, related to the plant and ETS.
```
--- Torn system (Block 2) of 6 iteration variables and 32 solved variables ---
Torn variables:
0     heaInd_79b2ee92.val.m_flow
1     heaInd_79b2ee92.hex.bal1.dp
2     disNet_0a70c94a.con[1].pipDisSup.dp
3     disNet_0a70c94a.ports_aCon[1].p
4     heaInd_79b2ee92.hex.port_a1.p
5     disNet_0a70c94a.con[2].pipDisSup.dp
6     disNet_0a70c94a.ports_aCon[2].p
7     heaInd_66f4d729.hex.bal1.dp
8     heaInd_66f4d729.hex.port_a1.p
9     heaInd_66f4d729.val.dp
10    disNet_0a70c94a.ports_bCon[2].p
11    heaInd_79b2ee92.val.dp
12    disNet_0a70c94a.ports_bCon[1].p
13    heaPla_2b7342d0.pumHW.val[2].m_flow
14    heaPla_2b7342d0.pumHW.val[1].dp
15    heaPla_2b7342d0.pumHW.pum[1].VMachine_flow
16    heaPla_2b7342d0.pumHW.pum[1].dp
17    heaPla_2b7342d0.pumHW.pum[1].port_b.p
18    heaPla_2b7342d0.boiHotWat.port_a.p
19    heaPla_2b7342d0.pumHW.m_flow
20    heaPla_2b7342d0.valByp.m_flow
21    heaPla_2b7342d0.valByp.dp
22    senTDisSup_e98c7d94.port_a.p
23    heaPla_2b7342d0.boiHotWat.val[2].dp
24    heaPla_2b7342d0.boiHotWat.boi[2].port_b.p
25    heaPla_2b7342d0.boiHotWat.boi[2].dp
26    heaPla_2b7342d0.boiHotWat.val[1].dp
27    heaPla_2b7342d0.boiHotWat.boi[1].port_b.p
28    heaPla_2b7342d0.boiHotWat.boi[1].dp
29    heaPla_2b7342d0.pumHW.val[2].dp
30    heaPla_2b7342d0.pumHW.pum[2].dp
31    heaPla_2b7342d0.pumHW.pum[2].port_b.p
```

The simulation with Dymola shows that, in the plant component

- the control of the pump speed is unstable,
- even when the control is stable, the district supply temperature set point is not tracked properly.

CentralHeatingPlant2

In the ETS component

- the building supply temperature set point is not tracked properly, partly due to the district supply temperature not being tracked, but also because
- the remote ETS is starved of HW, despite the control valve being fully open. This is also the case in `district_heating_system` (that simulates properly on my system) where the most remote ETS have 0 flow rate during the whole simulation. If we increased the pump head for this last model, I guess we would face the balancing issue discussed in a previous meeting. So I am not sure that this is easy to solve in the short term.

CentralHeatingPlant

I noticed several wrong orders of magnitude for the nominal pressure: for instance `heaInd_79b2ee92.dp1_nominal = 500 Pa`, which is about a hundred times less than typical. Also that parameter gets propagated to the HX model whereas it should be used to set `dpFixed_nominal` of the valve component to avoid an algebraic loop.

My conclusion is that 

- some significant validation work on the district heating system model is needed, prior to solving the simulation issue with JModelica (which may probably vanish when the hydronic and control get configured properly),
- we should implement a check of the load being met at the terminal unit level as part of the testing framework, and my guess is that several test failures will appear, revealing early on that some models are not properly configured.

**Comment by nllong** [comment]
This shouldn't have been merged, but it was. I'm reopening the branch as we need to resolve the issues.

**Comment by nllong** [comment]
We have figured that the control issues were just symptoms of the central plant not having the flexibility to supply the amount of heating/cooling. We'll address this is #280.

**Pull request merged**
