### PR TITLE
Teaser zone activate moisture balance

### PR DESCRIPTION
**Pull request by Helarga**
Latent load has been estimated as a fraction of the input sensible persons load, and based on the type of person's activities, this fraction fraLat changes. 

parameter Real fraLat= 0.8 "Fraction latent of sensible persons load = 0.8 for home, 1.25 for office.";

This PR partially solves the humidity evaluation for teaser Zones( modifications have made to teaser.py), still changes to the schema and system_parameters.py have to be done @nllong . The user will have the authority to change the parameter fraLat value as needed!

This change could me manually tested on Dymola by "check the box" of use_moisture_balance Boolean parameter and run the example on Dymola or Jmodelica and after finalizing the GMT changes run the py.test for the teaser package.

Relevant ticket: https://github.com/urbanopt/urbanopt-modelica/issues/57

### CODE REVIEW

**Comment by nllong** [comment]
I've added the fraction latent person variable to the schema and hooked it up directory in modelica... 
image

**Comment by Helarga** [comment]
> I've added the fraction latent person variable to the schema and hooked it up directly in modelica...
> 
> image

I think it wont be very clear to the user why the lat.load is 25% more than the persons sensible load.

**Comment by nllong** [comment]
isn't that the value for offices that you looked up?

**Comment by Helarga** [comment]
> isn't that the value for offices that you looked up?

oh, I thought that you are using the ration for home? yes for offices it was 1.25

**Pull request merged**
