### PR TITLE
Updated time series load file based on revisions to underlying model

### PR DESCRIPTION
**Pull request by amyeallen1**
I updated the mass flow rate temperature time series data after making revisions to the underlying model to improve it. I also updated the corresponding json file with system parameters accordingly. Thanks, Hagar, for all your advice on the model updates! This PR should not be merged until the failing tests are resolved. After running the tests on this branch and on develop, I don't think these modifications are causing any of the failing tests. 

@nllong @Helarga @vtnate Who should review this PR? Thanks!

### CODE REVIEW

**Comment by nllong** [comment]
I can't figure out why the flake8 and docs tests are not passing. Can you take a look @amyeallen1?

Nick

**Comment by amyeallen1** [comment]
Thanks for taking a look at it! I'm investigating. I think my not having run pre-commit is part of the problem. I'll follow up with you if I have more questions. @nllong

**Comment by amyeallen1** [comment]
Hi Nick--I ran pre-commit, and committed and pushed again, and that seems to have resolved the problem with flake8 and docs. The failing tests now seem to be due to the unit tests. Thanks for flagging this, and sorry about not having run pre-commit! @nllong

**Comment by nllong** [comment]
@vtnate -- this is now ready for review as the tests are passing. @amyeallen1 -- we are good to merge this once @vtnate reviews, correct?

**Review by vtnate — APPROVED** [review]
I don't have any insight into the details of the mos changes, but the tests pass so I'm good with it!

**Comment by amyeallen1** [comment]
Thanks, Nick, for bringing this up, and Nate, for reviewing it! The revisions I made to the underlying model had the effect of changing the numerical values in the time series data, and will have the effect of improving the ability of the Modelica-modeled systems to meet the bldg-level loads, but it wasn't expected to affect any of the functionality in the tests. @vtnate @nllong Is it okay for me to go ahead and merge?

**Comment by vtnate** [comment]
I'm pretty sure I'm not a good reviewer for this. :) What changes to the underlying model did you make? Is that in another PR? How can we confirm that this change does make things better if the unit tests aren't applicable in this case?

**Comment by amyeallen1** [comment]
Thanks for bringing up those points, Nate! I'm just writing this here for posterity....Hagar reviewed the performance of the model with this new time series data as input. In the future, perhaps the documentation for the GMT could include some plots illustrating the performance of the test cases to document that they work as intended.

**Pull request merged**
