### PR TITLE
Add sphinx configuration for generating documentation

### PR DESCRIPTION
**Pull request by macintoshpie**
#### What does this PR accomplish?
Sets up sphinx documentation generator to document the GMT tool and adds a script for updating the documentation on github.
#### How should this be manually tested?
First, make sure the site looks decent. It should approximate the other urban opt geojson documentation sites as best as possible, e.g. [this one](https://docs.urbanopt.net/urbanopt-geojson-gem/rdoc/URBANopt/GeoJSON/Building.html).

Checkout the github pages site (to be added from the `gh-pages` branch) and verify all required elements are documented. Also try updating the documentation by editing a module/class/function docstring, then running `./docs/publish_docs.sh`, and verify the `gh-pages` branch was updated.
#### What are the relevant tickets?
#130 
#### Screenshots (if appropriate)
Screen Shot 2020-09-29 at 2 04 32 PM

### CODE REVIEW

**Comment by macintoshpie** [comment]
@nllong or someone with permission to do so, can we setup the github pages to serve from `gh-pages` branch?

**Review by nllong — CHANGES_REQUESTED** [review]
cool! Can you fix the pre-commit errors:
https://travis-ci.org/github/urbanopt/geojson-modelica-translator/jobs/731396390#L283

**Comment by nllong** [comment]
Done: 
image

Anything else on this page? 

@vtnate -- what should the CNAME be on the project assuming we want it to be similar to one of these: https://docs.urbanopt.net/urbanopt-reopt-gem/

**Comment by vtnate** [comment]
@macintoshpie docs.urbanopt.net are served from this repo: https://github.com/urbanopt/urbanopt.github.io which has this CNAME file in it: https://github.com/urbanopt/urbanopt.github.io/blob/develop/CNAME

Brian Schiller (#GitBlame) helped us with the rdocs linked in your comment, for instance with this publishing script: https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/deploy_docs.sh. There may be additional examples you could use in that repo.

**Comment by macintoshpie** [comment]
@nllong 
> what should the CNAME be on the project assuming we want it to be similar to one of these: https://docs.urbanopt.net/urbanopt-reopt-gem/

No need to do this, github automatically puts these docs at https://docs.urbanopt.net/geojson-modelica-translator/

Ref:
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites

**Comment by nllong** [comment]
Oh good! Then I think we are ready? Do I need to set the style to something? It looks pretty naked here: https://docs.urbanopt.net/geojson-modelica-translator/



Da: Ted Summer <notifications@github.com>
Risposta: urbanopt/geojson-modelica-translator <reply@reply.github.com>
Data: martedì 29 settembre 2020 16:10
A: urbanopt/geojson-modelica-translator <geojson-modelica-translator@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [urbanopt/geojson-modelica-translator] Add sphinx configuration for generating documentation (#185)


@nllong<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=02%7C01%7Cnicholas.long%40nrel.gov%7C5948f9dbab85412c740d08d864c46de4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637370142105362888&sdata=EQpK5m%2BTRSDp794SWeUN7%2FAbEvd0yoMExONZt0KmHEs%3D&reserved=0>

what should the CNAME be on the project assuming we want it to be similar to one of these: https://docs.urbanopt.net/urbanopt-reopt-gem/<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.urbanopt.net%2Furbanopt-reopt-gem%2F&data=02%7C01%7Cnicholas.long%40nrel.gov%7C5948f9dbab85412c740d08d864c46de4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637370142105362888&sdata=CMHLEWuR3ePJfBSe7ksooc4S9trlLVuSkuvpCHUoFUs%3D&reserved=0>

No need to do this, github automatically puts these docs at https://docs.urbanopt.net/geojson-modelica-translator/<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.urbanopt.net%2Fgeojson-modelica-translator%2F&data=02%7C01%7Cnicholas.long%40nrel.gov%7C5948f9dbab85412c740d08d864c46de4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637370142105372843&sdata=8fJu1Hs2rhrYlckpdkUkmLlhoURkpnYIspfWfBeIiVQ%3D&reserved=0>

Ref:
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Ffree-pro-team%40latest%2Fgithub%2Fworking-with-github-pages%2Fabout-github-pages%23types-of-github-pages-sites&data=02%7C01%7Cnicholas.long%40nrel.gov%7C5948f9dbab85412c740d08d864c46de4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637370142105372843&sdata=pgg%2FjBxH96%2By9Qg3yZDMIUFokXaQCLcFs%2BcjK8q%2FWsI%3D&reserved=0>

**Comment by macintoshpie** [comment]
Are you seeing the same thing as the screenshot in the PR description? It's a bit minimal, but I tried to keep it similar to what already exists for the ruby repos.

If you're not seeing that same screen, you might be having the same issue I was, getting 404s for static assets. I added the `.nojekyll` file to the repo to fix this here: 1a3d51d. I'm not sure when the cache will expire, but I've confirmed that when it does it should work by loading the page over my mobile network

**Comment by nllong** [comment]
No I’m not seeing the same thing. What you have looks right. I’m sure it is NREL’s cache. It looks find on my phone. False alarm then.



Da: Ted Summer <notifications@github.com>
Risposta: urbanopt/geojson-modelica-translator <reply@reply.github.com>
Data: martedì 29 settembre 2020 16:20
A: urbanopt/geojson-modelica-translator <geojson-modelica-translator@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [urbanopt/geojson-modelica-translator] Add sphinx configuration for generating documentation (#185)


Are you seeing the same thing as the screenshot in the PR description? It's a bit minimal, but I tried to keep it similar to what already exists for the ruby repos.

If you're not seeing that same screen, you might be having the same issue I was, getting 404s for static assets. I added the .nojekyll file to the repo to fix this here: 1a3d51d<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Furbanopt%2Fgeojson-modelica-translator%2Fcommit%2F1a3d51db4cdd26a5cad3348560e446f61998f527&data=02%7C01%7Cnicholas.long%40nrel.gov%7Cb2a8604f3da34466e25108d864c5cd34%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637370147999324425&sdata=nGOWv2aRP4mwGrUrkhvIYoYe5d3srIcGjC%2FksiNrK3k%3D&reserved=0>. I'm not sure when the cache will expire, but I've confirmed that when it does it should work by loading the page over my mobile network

**Comment by nllong** [comment]
Oops, sorry @macintoshpie -- is this ready for review? (I just triggered the state change.)

**Review by nllong — APPROVED** [review]

**Pull request merged**
